apiVersion: 1

contactPoints:
    - orgId: 1
      name: ntfy
      receivers:
          - uid: ntfy-alerts
            type: webhook
            settings:
                url: http://grafana-ntfy:8080
                httpMethod: POST
                authorization_scheme: Bearer
                authorization_credentials: $NTFY_TOKEN
                title: >-
                    {{ if eq .Status "firing" }}FIRING{{ else }}RESOLVED{{ end }}: {{ (index .Alerts 0).Labels.alertname }}
                message: >-
                    {{ (index .Alerts 0).Annotations.summary }}
            disableResolveMessage: false
