apiVersion: 1

templates:
    - orgId: 1
      name: ntfy
      template: |
          {{ define "ntfy.title" -}}
          {{ if eq .Status "firing" }}FIRING{{ else }}RESOLVED{{ end }}: {{ (index .Alerts 0).Labels.alertname }}
          {{- end }}

          {{ define "ntfy.message" -}}
          {{ range .Alerts -}}
          {{ .Annotations.summary }}
          {{ end -}}
          {{- end }}
