apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: influxdb
    version: 5
    jsonData:
      version: Flux
      organization: homelab
      defaultBucket: glances
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Token $INFLUXDB_ADMIN_TOKEN
    editable: false
